NAME = bsqi
CC= cc
SOURCE_DIR = srcs/
HEADER_DIR = includes/
SRCS =	srcs/ft_putchar 
	srcs/ft_strcmp
	srcs/ft_swap
FLAGS = -Wall -Wextra -Werror
MAIN = main.c

OBJS = $(SRCS:.c=.o)

all:

clean:

fclean: clean

re: fclean all

.PHONY: all clean fclean re

